<?php

namespace Database\Seeders;

use App\Models\Stock\SousCategorie;
use Illuminate\Database\Seeder;

class SousCategoriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        SousCategorie::insert([
            ['nom' => 'plaquettes de frein', 'user' => 1, 'categorie' => 2],
            ['nom' => 'disques de frein', 'user' => 1, 'categorie' => 2],
            ['nom' => 'etrier de frein', 'user' => 1, 'categorie' => 2],
            ['nom' => 'flexible de frein', 'user' => 1, 'categorie' => 2],
            ['nom' => 'contacteur de témoin d\'usure plaquette de frein', 'user' => 1, 'categorie' => 2],
            ['nom' => 'kit de réparation étrier de frein', 'user' => 1, 'categorie' => 2],
            ['nom' => 'liquide de frein', 'user' => 1, 'categorie' => 2],
            ['nom' => 'machoîres de frein', 'user' => 1, 'categorie' => 2],
            ['nom' => 'capteurs ABS', 'user' => 1, 'categorie' => 2],
            ['nom' => 'kit de freins', 'user' => 1, 'categorie' => 2],
            ['nom' => 'câble de frein à main', 'user' => 1, 'categorie' => 2],
            ['nom' => 'kit d\'accessoire mâchoires de frein', 'user' => 1, 'categorie' => 2],
            ['nom' => 'kit douille de guidage étrier de frein', 'user' => 1, 'categorie' => 2],
            ['nom' => 'cylindre de roue', 'user' => 1, 'categorie' => 2],
            ['nom' => 'deflecteur disque de frein', 'user' => 1, 'categorie' => 2],
            ['nom' => 'mâchoires de frein à main', 'user' => 1, 'categorie' => 2],
            ['nom' => 'freins à tambour', 'user' => 1, 'categorie' => 2],
            ['nom' => 'tambour de frein', 'user' => 1, 'categorie' => 2],
            ['nom' => 'maitre cylindre de frein', 'user' => 1, 'categorie' => 2],
            ['nom' => 'contacteur de feux stop', 'user' => 1, 'categorie' => 2],
            ['nom' => 'bague ABS', 'user' => 1, 'categorie' => 2],
            ['nom' => 'support d\'étrier de frein', 'user' => 1, 'categorie' => 2],
            ['nom' => 'piston d\'étrier de frein', 'user' => 1, 'categorie' => 2],
            ['nom' => 'pompe à vide de freinage', 'user' => 1, 'categorie' => 2],
            ['nom' => 'canalisation de frein', 'user' => 1, 'categorie' => 2],
            ['nom' => 'régulateur de freinage', 'user' => 1, 'categorie' => 2],
            ['nom' => 'vase d\'expansion liquide de frein', 'user' => 1, 'categorie' => 2],
            ['nom' => 'bloc ABS', 'user' => 1, 'categorie' => 2],
            ['nom' => 'huile moteur', 'user' => 1, 'categorie' => 3],
            ['nom' => 'support moteur', 'user' => 1, 'categorie' => 3],
            ['nom' => 'bouchon de carter d\'huile', 'user' => 1, 'categorie' => 3],
            ['nom' => 'vis de culasse', 'user' => 1, 'categorie' => 3],
            ['nom' => 'jauge à l\'huile', 'user' => 1, 'categorie' => 3],
            ['nom' => 'reniflard d\'huile', 'user' => 1, 'categorie' => 3],
            ['nom' => 'carter d\'huile', 'user' => 1, 'categorie' => 3],
            ['nom' => 'bouchon goulotte de remplissage d\'huile', 'user' => 1, 'categorie' => 3],
            ['nom' => 'coussinet de bielle', 'user' => 1, 'categorie' => 3],
            ['nom' => 'poussoir hydraulique', 'user' => 1, 'categorie' => 3],
            ['nom' => 'segment de piston', 'user' => 1, 'categorie' => 3],
            ['nom' => 'capteur niveau d\'huile', 'user' => 1, 'categorie' => 3],
            ['nom' => 'jeu de joints d\'étancheité carter de vilebrequin', 'user' => 1, 'categorie' => 3],
            ['nom' => 'soupape d\'échappement', 'user' => 1, 'categorie' => 3],
            ['nom' => 'pochette joint de culasse', 'user' => 1, 'categorie' => 3],
            ['nom' => 'arbre à cames', 'user' => 1, 'categorie' => 3],
            ['nom' => 'pompe à l\'huile', 'user' => 1, 'categorie' => 3],
            ['nom' => 'soupape d\'admission', 'user' => 1, 'categorie' => 3],
            ['nom' => 'coussinet de vilbrequin', 'user' => 1, 'categorie' => 3],
            ['nom' => 'culbuteur', 'user' => 1, 'categorie' => 3],
            ['nom' => 'kit de montage compresseur', 'user' => 1, 'categorie' => 3],
            ['nom' => 'piston', 'user' => 1, 'categorie' => 3],
            ['nom' => 'collecteur d\'admission', 'user' => 1, 'categorie' => 3],
            ['nom' => 'carter de distribution', 'user' => 1, 'categorie' => 3],
            ['nom' => 'cache-culbuteur', 'user' => 1, 'categorie' => 3],
            ['nom' => 'culasse', 'user' => 1, 'categorie' => 3],
            ['nom' => 'pompe d\'injecteur d\'air secondaire', 'user' => 1, 'categorie' => 3],
            ['nom' => 'bloc-moteur', 'user' => 1, 'categorie' => 3],
            ['nom' => 'vilebrequin', 'user' => 1, 'categorie' => 3],
            ['nom' => 'roulement de roue', 'user' => 1, 'categorie' => 4],
            ['nom' => 'biellette de barre stabilisatrice', 'user' => 1, 'categorie' => 4],
            ['nom' => 'bras de suspension', 'user' => 1, 'categorie' => 4],
            ['nom' => 'rotule de suspension', 'user' => 1, 'categorie' => 4],
            ['nom' => 'silent bloc de bras de suspension', 'user' => 1, 'categorie' => 4],
            ['nom' => 'silent bloc de barre stabilisatrice', 'user' => 1, 'categorie' => 4],
            ['nom' => 'boulon de roue', 'user' => 1, 'categorie' => 4],
            ['nom' => 'moyeux de roue', 'user' => 1, 'categorie' => 4],
            ['nom' => 'kit de réparation bras de suspension', 'user' => 1, 'categorie' => 4],
            ['nom' => 'support d\'essieu', 'user' => 1, 'categorie' => 4],
            ['nom' => 'élargissement de voie', 'user' => 1, 'categorie' => 4],
            ['nom' => 'fusée d\'essieu', 'user' => 1, 'categorie' => 4],
            ['nom' => 'barre stabilisatrice', 'user' => 1, 'categorie' => 4],
            ['nom' => 'écrou de roue', 'user' => 1, 'categorie' => 4],
            ['nom' => 'différenciel', 'user' => 1, 'categorie' => 4],
            ['nom' => 'courroie poly v', 'user' => 1, 'categorie' => 5],
            ['nom' => 'pompe à eau + kit de courroie de distrubution', 'user' => 1, 'categorie' => 5],
            ['nom' => 'kit de distrubution', 'user' => 1, 'categorie' => 5],
            ['nom' => 'kit de courroie d\'accéssoire', 'user' => 1, 'categorie' => 5],
            ['nom' => 'galet tendeur', 'user' => 1, 'categorie' => 5],
            ['nom' => 'courroie trapézoidale', 'user' => 1, 'categorie' => 5],
            ['nom' => 'tendeur de courroie', 'user' => 1, 'categorie' => 5],
            ['nom' => 'galet enrouleur de courroie d\'accessoire', 'user' => 1, 'categorie' => 5],
            ['nom' => 'kit chaîne de distribution', 'user' => 1, 'categorie' => 5],
            ['nom' => 'tendeur de chaîne de distribution', 'user' => 1, 'categorie' => 5],
            ['nom' => 'chaîne de distribution', 'user' => 1, 'categorie' => 5],
            ['nom' => 'bougie d\'allumage', 'user' => 1, 'categorie' => 6],
            ['nom' => 'bobines d\'allumage', 'user' => 1, 'categorie' => 6],
            ['nom' => 'bougie de préchauffage', 'user' => 1, 'categorie' => 6],
            ['nom' => 'faisceau d\'allumage', 'user' => 1, 'categorie' => 6],
            ['nom' => 'tête d\'allumeur', 'user' => 1, 'categorie' => 6],
            ['nom' => 'doigt d\'allumeur', 'user' => 1, 'categorie' => 6],
            ['nom' => 'temporisateur de préchauffage', 'user' => 1, 'categorie' => 6],
            ['nom' => 'allumeur', 'user' => 1, 'categorie' => 6],
            ['nom' => 'capteur de cliquetis', 'user' => 1, 'categorie' => 6],
            ['nom' => 'module d\'allumage', 'user' => 1, 'categorie' => 6],
            ['nom' => 'sonde lambda', 'user' => 1, 'categorie' => 7],
            ['nom' => 'silencieux arrière', 'user' => 1, 'categorie' => 7],
            ['nom' => 'vanne EGR', 'user' => 1, 'categorie' => 7],
            ['nom' => 'joint d\'échappement', 'user' => 1, 'categorie' => 7],
            ['nom' => 'fixation pot d\'échappement', 'user' => 1, 'categorie' => 7],
            ['nom' => 'silencieux intermédiaire', 'user' => 1, 'categorie' => 7],
            ['nom' => "kit d'assemblage système d'chappement", 'user' => 1, 'categorie' => 7],
            ['nom' => "collier d'echappement", 'user' => 1, 'categorie' => 7],
            ['nom' => "tuyau d'échappement", 'user' => 1, 'categorie' => 7],
            ['nom' => "tresse d'échappement", 'user' => 1, 'categorie' => 7],
            ['nom' => "turbocompresseur", 'user' => 1, 'categorie' => 7],
            ['nom' => 'catalyseur', 'user' => 1, 'categorie' => 7],
            ['nom' => 'filtre à particules', 'user' => 1, 'categorie' => 7],
            ['nom' => 'silencieux avant', 'user' => 1, 'categorie' => 7],
            ['nom' => "kit d'assemblage silencieux", 'user' => 1, 'categorie' => 7],
            ['nom' => "kit d'assemblage catalyseur", 'user' => 1, 'categorie' => 7],
            ['nom' => "collecteur d'échappement", 'user' => 1, 'categorie' => 7],
            ['nom' => "protection thermique d'échappement", 'user' => 1, 'categorie' => 7],
            ['nom' => "embouts d'échappement", 'user' => 1, 'categorie' => 7],
            ['nom' => "kit de montage collecteur des gaz d'échappement", 'user' => 1, 'categorie' => 7],
            ['nom' => "filtre à huile", 'user' => 1, 'categorie' => 8],
            ['nom' => "filtre à air", 'user' => 1, 'categorie' => 8],
            ['nom' => "filtre d'habitacle", 'user' => 1, 'categorie' => 8],
            ['nom' => "filtre à carburant", 'user' => 1, 'categorie' => 8],
            ['nom' => "filtre à air sport", 'user' => 1, 'categorie' => 8],
            ['nom' => "vérin de hayon", 'user' => 1, 'categorie' => 9],
            ['nom' => "rétroviseur extérieur", 'user' => 1, 'categorie' => 9],
            ['nom' => "feu arrière", 'user' => 1, 'categorie' => 9],
            ['nom' => "glace rétroviseur", 'user' => 1, 'categorie' => 9],
            ['nom' => "phares", 'user' => 1, 'categorie' => 9],
            ['nom' => "feux clignotant", 'user' => 1, 'categorie' => 9],
            ['nom' => "pare-boue", 'user' => 1, 'categorie' => 9],
            ['nom' => "anti-brouillard", 'user' => 1, 'categorie' => 9],
            ['nom' => "grille de pare-chocs", 'user' => 1, 'categorie' => 9],
            ['nom' => "éclairage de plaque d'immatriculation", 'user' => 1, 'categorie' => 9],
            ['nom' => "poignée de porte", 'user' => 1, 'categorie' => 9],
            ['nom' => "pare-chocs", 'user' => 1, 'categorie' => 9],
            ['nom' => "grille de callandre", 'user' => 1, 'categorie' => 9],
            ['nom' => "vérin de capot", 'user' => 1, 'categorie' => 9],
            ['nom' => "aile", 'user' => 1, 'categorie' => 9],
            ['nom' => "coque de rétroviseur", 'user' => 1, 'categorie' => 9],
            ['nom' => "support de pare-chocs", 'user' => 1, 'categorie' => 9],
            ['nom' => "portes composants", 'user' => 1, 'categorie' => 9],
            ['nom' => "capot", 'user' => 1, 'categorie' => 9],
            ['nom' => "feu stop additionnel", 'user' => 1, 'categorie' => 9],
            ['nom' => "attelage remorque", 'user' => 1, 'categorie' => 9],
            ['nom' => "baguette", 'user' => 1, 'categorie' => 9],
            ['nom' => "face avant", 'user' => 1, 'categorie' => 9],
            ['nom' => "renfort de pare-chocs", 'user' => 1, 'categorie' => 9],
            ['nom' => "bas de caisse", 'user' => 1, 'categorie' => 9],
            ['nom' => "catadioptre arrière", 'user' => 1, 'categorie' => 9],
            ['nom' => "feu de brouillard arrière", 'user' => 1, 'categorie' => 9],
            ['nom' => "fermeture centralisée", 'user' => 1, 'categorie' => 9],
            ['nom' => "serrure de hayon", 'user' => 1, 'categorie' => 9],
            ['nom' => "spoiler pare-choc", 'user' => 1, 'categorie' => 9],
            ['nom' => "cache moteur", 'user' => 1, 'categorie' => 9],
            ['nom' => "feu de position", 'user' => 1, 'categorie' => 9],
            ['nom' => "élargisseur d'aile", 'user' => 1, 'categorie' => 9],
            ['nom' => "feux diurne", 'user' => 1, 'categorie' => 9],
            ['nom' => "passage de roue", 'user' => 1, 'categorie' => 9],
            ['nom' => "hayon de coffre", 'user' => 1, 'categorie' => 9],
            ['nom' => "joint de vitre", 'user' => 1, 'categorie' => 9],
            ['nom' => "verre de phare", 'user' => 1, 'categorie' => 9],
            ['nom' => "joint de porte", 'user' => 1, 'categorie' => 9],
            ['nom' => "feu de recul", 'user' => 1, 'categorie' => 9],
            ['nom' => "emblèmes", 'user' => 1, 'categorie' => 9],
            ['nom' => "feux stop", 'user' => 1, 'categorie' => 9],
            ['nom' => "longeron", 'user' => 1, 'categorie' => 9],
            ['nom' => "amortisseur", 'user' => 1, 'categorie' => 10],
            ['nom' => "coupelle d'amortisseur", 'user' => 1, 'categorie' => 10],
            ['nom' => "ressort de suspension", 'user' => 1, 'categorie' => 10],
            ['nom' => "soufflet d'amortisseur & buttée élastique suspension", 'user' => 1, 'categorie' => 10],
            ['nom' => "kit de ressort", 'user' => 1, 'categorie' => 10],
            ['nom' => "patin de ressort", 'user' => 1, 'categorie' => 10],
            ['nom' => "lame de ressort", 'user' => 1, 'categorie' => 10],
            ['nom' => "suspension pneumatique", 'user' => 1, 'categorie' => 10],
            ['nom' => "jeu de suspensions ressorts amortisseurs", 'user' => 1, 'categorie' => 10],
            ['nom' => "accumulateur de suspension", 'user' => 1, 'categorie' => 10],
            ['nom' => "essuie-glaces", 'user' => 1, 'categorie' => 11],
            ['nom' => "bras d'essuie-glace", 'user' => 1, 'categorie' => 11],
            ['nom' => "pompe de lave-glace", 'user' => 1, 'categorie' => 11],
            ['nom' => "moteur d'essuie-glace", 'user' => 1, 'categorie' => 11],
            ['nom' => "tringlerie d'essuie-glace", 'user' => 1, 'categorie' => 11],
            ['nom' => "gicleur d'essuie-glace", 'user' => 1, 'categorie' => 11],
            ['nom' => "bocal lave-glace", 'user' => 1, 'categorie' => 11],
            ['nom' => "caoutchouc d'essuie-glace", 'user' => 1, 'categorie' => 11],
            ['nom' => "calorstat", 'user' => 1, 'categorie' => 12],
            ['nom' => "pompe à eau", 'user' => 1, 'categorie' => 12],
            ['nom' => "radiateur de réfroidissement moteur", 'user' => 1, 'categorie' => 12],
            ['nom' => "sonde de température liquide de réfroidissement", 'user' => 1, 'categorie' => 12],
            ['nom' => "vase d'expansion de liquide de réfroidissement", 'user' => 1, 'categorie' => 12],
            ['nom' => "bouchon liquide de réfroidissement", 'user' => 1, 'categorie' => 12],
            ['nom' => "échangeur air", 'user' => 1, 'categorie' => 12],
            ['nom' => "ventilateur de radiateur", 'user' => 1, 'categorie' => 12],
            ['nom' => "interrupteur de température ventilateur de radiateur", 'user' => 1, 'categorie' => 12],
            ['nom' => "radiateur d'huile", 'user' => 1, 'categorie' => 12],
            ['nom' => "embrayage ventilateur de radiateur", 'user' => 1, 'categorie' => 12],
            ['nom' => "bouchon de radiateur", 'user' => 1, 'categorie' => 12],
            ['nom' => "antigel", 'user' => 1, 'categorie' => 12],
            ['nom' => "rotule de direction", 'user' => 1, 'categorie' => 13],
            ['nom' => "rotule axiale", 'user' => 1, 'categorie' => 13],
            ['nom' => "soufflet de direction", 'user' => 1, 'categorie' => 13],
            ['nom' => "biellette de direction", 'user' => 1, 'categorie' => 13],
            ['nom' => "pompe hydraulique de direction assistée", 'user' => 1, 'categorie' => 13],
            ['nom' => "huile hydraulique", 'user' => 1, 'categorie' => 13],
            ['nom' => "crémaillère de direction", 'user' => 1, 'categorie' => 13],
            ['nom' => "amortisseur de direction", 'user' => 1, 'categorie' => 13],
            ['nom' => "liquide direction assistée", 'user' => 1, 'categorie' => 13],
            ['nom' => "capteur d'angle de braquage", 'user' => 1, 'categorie' => 13],
            ['nom' => "colonne de direction + direction assistée électrique", 'user' => 1, 'categorie' => 13],
        ]);
    }
}
