<?php

namespace Database\Seeders;

use App\Models\Stock\SousCategorie;
use Illuminate\Database\Seeder;

class SousCategoriesSlugSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $categorie = SousCategorie::where('id', 1)->get()->first();
        $categorie->slug = 'plaq-frein';
        $categorie->save();
        $categorie = SousCategorie::where('id', 2)->get()->first();
        $categorie->slug = 'disq-frein';
        $categorie->save();
        $categorie = SousCategorie::where('id', 3)->get()->first();
        $categorie->slug = 'etr-frein';
        $categorie->save();
        $categorie = SousCategorie::where('id', 4)->get()->first();
        $categorie->slug = 'flex-frein';
        $categorie->save();
        $categorie = SousCategorie::where('id', 5)->get()->first();
        $categorie->slug = 'usure-plaq';
        $categorie->save();
        $categorie = SousCategorie::where('id', 6)->get()->first();
        $categorie->slug = 'kit-rep-etrfrein';
        $categorie->save();
        $categorie = SousCategorie::where('id', 7)->get()->first();
        $categorie->slug = 'liq-frein';
        $categorie->save();
        $categorie = SousCategorie::where('id', 8)->get()->first();
        $categorie->slug = 'mach-frein';
        $categorie->save();
        $categorie = SousCategorie::where('id', 9)->get()->first();
        $categorie->slug = 'capt-abs';
        $categorie->save();
        $categorie = SousCategorie::where('id', 10)->get()->first();
        $categorie->slug = 'kit-frein';
        $categorie->save();
        $categorie = SousCategorie::where('id', 11)->get()->first();
        $categorie->slug = 'cabl-frein-main';
        $categorie->save();
        $categorie = SousCategorie::where('id', 12)->get()->first();
        $categorie->slug = 'kit-acc-mach-frein';
        $categorie->save();
        $categorie = SousCategorie::where('id', 13)->get()->first();
        $categorie->slug = 'kit-guid-etrfrein';
        $categorie->save();
        $categorie = SousCategorie::where('id', 14)->get()->first();
        $categorie->slug = 'cylin-roue';
        $categorie->save();
        $categorie = SousCategorie::where('id', 15)->get()->first();
        $categorie->slug = 'deflect-disqfrein';
        $categorie->save();
        $categorie = SousCategorie::where('id', 16)->get()->first();
        $categorie->slug = 'mach-frein-main';
        $categorie->save();
        $categorie = SousCategorie::where('id', 17)->get()->first();
        $categorie->slug = 'frein-tamb';
        $categorie->save();
        $categorie = SousCategorie::where('id', 18)->get()->first();
        $categorie->slug = 'tamb-frein';
        $categorie->save();
        $categorie = SousCategorie::where('id', 19)->get()->first();
        $categorie->slug = 'maitr-cylin-frein';
        $categorie->save();
        $categorie = SousCategorie::where('id', 20)->get()->first();
        $categorie->slug = 'contact-feustop';
        $categorie->save();
        $categorie = SousCategorie::where('id', 21)->get()->first();
        $categorie->slug = 'bag-abs';
        $categorie->save();
        $categorie = SousCategorie::where('id', 22)->get()->first();
        $categorie->slug = 'supp-etrfrein';
        $categorie->save();
        $categorie = SousCategorie::where('id', 23)->get()->first();
        $categorie->slug = 'pist-etrfrein';
        $categorie->save();
        $categorie = SousCategorie::where('id', 24)->get()->first();
        $categorie->slug = 'pomp-vid-frein';
        $categorie->save();
        $categorie = SousCategorie::where('id', 25)->get()->first();
        $categorie->slug = 'canal-frein';
        $categorie->save();
        $categorie = SousCategorie::where('id', 26)->get()->first();
        $categorie->slug = 'régul-frein';
        $categorie->save();
        $categorie = SousCategorie::where('id', 27)->get()->first();
        $categorie->slug = 'expvase-liq-frein';
        $categorie->save();
        $categorie = SousCategorie::where('id', 28)->get()->first();
        $categorie->slug = 'bloc-abs';
        $categorie->save();
        $categorie = SousCategorie::where('id', 29)->get()->first();
        $categorie->slug = 'huil-moteur';
        $categorie->save();
        $categorie = SousCategorie::where('id', 30)->get()->first();
        $categorie->slug = 'supp-moteur';
        $categorie->save();
        $categorie = SousCategorie::where('id', 31)->get()->first();
        $categorie->slug = 'cartbouch-huile';
        $categorie->save();
        $categorie = SousCategorie::where('id', 32)->get()->first();
        $categorie->slug = 'vis-culass';
        $categorie->save();
        $categorie = SousCategorie::where('id', 33)->get()->first();
        $categorie->slug = 'jaug-huil';
        $categorie->save();
        $categorie = SousCategorie::where('id', 34)->get()->first();
        $categorie->slug = 'renifl-huil';
        $categorie->save();
        $categorie = SousCategorie::where('id', 35)->get()->first();
        $categorie->slug = 'cart-huil';
        $categorie->save();
        $categorie = SousCategorie::where('id', 36)->get()->first();
        $categorie->slug = 'goulbouch-rempl-huil';
        $categorie->save();
        $categorie = SousCategorie::where('id', 37)->get()->first();
        $categorie->slug = 'couss-biel';
        $categorie->save();
        $categorie = SousCategorie::where('id', 38)->get()->first();
        $categorie->slug = 'pouss-hydr';
        $categorie->save();
        $categorie = SousCategorie::where('id', 39)->get()->first();
        $categorie->slug = 'segm-pist';
        $categorie->save();
        $categorie = SousCategorie::where('id', 40)->get()->first();
        $categorie->slug = 'capt-nivhuil';
        $categorie->save();
        $categorie = SousCategorie::where('id', 41)->get()->first();
        $categorie->slug = 'joinétanch-cartvilbreq';
        $categorie->save();
        $categorie = SousCategorie::where('id', 42)->get()->first();
        $categorie->slug = 'soupap-echapmnt';
        $categorie->save();
        $categorie = SousCategorie::where('id', 43)->get()->first();
        $categorie->slug = 'pochte-join-culass';
        $categorie->save();
        $categorie = SousCategorie::where('id', 44)->get()->first();
        $categorie->slug = 'arbre-cam';
        $categorie->save();
        $categorie = SousCategorie::where('id', 45)->get()->first();
        $categorie->slug = 'pomp-huil';
        $categorie->save();
        $categorie = SousCategorie::where('id', 46)->get()->first();
        $categorie->slug = 'soupap-admissn';
        $categorie->save();
        $categorie = SousCategorie::where('id', 47)->get()->first();
        $categorie->slug = 'couss-vilbreq';
        $categorie->save();
        $categorie = SousCategorie::where('id', 48)->get()->first();
        $categorie->slug = 'culbuteur';
        $categorie->save();
        $categorie = SousCategorie::where('id', 49)->get()->first();
        $categorie->slug = 'kit-mont-compress';
        $categorie->save();
        $categorie = SousCategorie::where('id', 50)->get()->first();
        $categorie->slug = 'piston';
        $categorie->save();
        $categorie = SousCategorie::where('id', 51)->get()->first();
        $categorie->slug = 'collect-admissn';
        $categorie->save();
        $categorie = SousCategorie::where('id', 52)->get()->first();
        $categorie->slug = 'cart-distrib';
        $categorie->save();
        $categorie = SousCategorie::where('id', 53)->get()->first();
        $categorie->slug = 'cach-culbut';
        $categorie->save();
        $categorie = SousCategorie::where('id', 54)->get()->first();
        $categorie->slug = 'culasse';
        $categorie->save();
        $categorie = SousCategorie::where('id', 55)->get()->first();
        $categorie->slug = 'pomp-airinject-scnd';
        $categorie->save();
        $categorie = SousCategorie::where('id', 56)->get()->first();
        $categorie->slug = 'bloc-moteur';
        $categorie->save();
        $categorie = SousCategorie::where('id', 57)->get()->first();
        $categorie->slug = 'vilebrequin';
        $categorie->save();
        $categorie = SousCategorie::where('id', 58)->get()->first();
        $categorie->slug = 'roulmnt-roue';
        $categorie->save();
        $categorie = SousCategorie::where('id', 59)->get()->first();
        $categorie->slug = 'bielte-bar-stab';
        $categorie->save();
        $categorie = SousCategorie::where('id', 60)->get()->first();
        $categorie->slug = 'bras-susp';
        $categorie->save();
        $categorie = SousCategorie::where('id', 61)->get()->first();
        $categorie->slug = 'rot-susp';
        $categorie->save();
        $categorie = SousCategorie::where('id', 62)->get()->first();
        $categorie->slug = 'silbloc-bras-susp';
        $categorie->save();
        $categorie = SousCategorie::where('id', 63)->get()->first();
        $categorie->slug = 'silbloc-bar-stab';
        $categorie->save();
        $categorie = SousCategorie::where('id', 64)->get()->first();
        $categorie->slug = 'boulon-roue';
        $categorie->save();
        $categorie = SousCategorie::where('id', 65)->get()->first();
        $categorie->slug = 'moyeux-roue';
        $categorie->save();
        $categorie = SousCategorie::where('id', 66)->get()->first();
        $categorie->slug = 'kit-rep-bras-susp';
        $categorie->save();
        $categorie = SousCategorie::where('id', 67)->get()->first();
        $categorie->slug = 'supp-essieu';
        $categorie->save();
        $categorie = SousCategorie::where('id', 68)->get()->first();
        $categorie->slug = 'elargismnt-voie';
        $categorie->save();
        $categorie = SousCategorie::where('id', 69)->get()->first();
        $categorie->slug = 'fusée-essieu';
        $categorie->save();
        $categorie = SousCategorie::where('id', 70)->get()->first();
        $categorie->slug = 'bar-stab';
        $categorie->save();
        $categorie = SousCategorie::where('id', 71)->get()->first();
        $categorie->slug = 'écrou-roue';
        $categorie->save();
        $categorie = SousCategorie::where('id', 72)->get()->first();
        $categorie->slug = 'différenciel';
        $categorie->save();
        $categorie = SousCategorie::where('id', 73)->get()->first();
        $categorie->slug = 'courroie-polyv';
        $categorie->save();
        $categorie = SousCategorie::where('id', 74)->get()->first();
        $categorie->slug = 'pompeau-kit-couroi-distrib';
        $categorie->save();
        $categorie = SousCategorie::where('id', 75)->get()->first();
        $categorie->slug = 'kit-distrib';
        $categorie->save();
        $categorie = SousCategorie::where('id', 76)->get()->first();
        $categorie->slug = 'kit-couroi-acc';
        $categorie->save();
        $categorie = SousCategorie::where('id', 77)->get()->first();
        $categorie->slug = 'galet-tendeur';
        $categorie->save();
        $categorie = SousCategorie::where('id', 78)->get()->first();
        $categorie->slug = 'courroie-trapez';
        $categorie->save();
        $categorie = SousCategorie::where('id', 79)->get()->first();
        $categorie->slug = 'tendeur-courroie';
        $categorie->save();
        $categorie = SousCategorie::where('id', 80)->get()->first();
        $categorie->slug = 'galet-enroul-couroi-acc';
        $categorie->save();
        $categorie = SousCategorie::where('id', 81)->get()->first();
        $categorie->slug = 'kit-chain-distrib';
        $categorie->save();
        $categorie = SousCategorie::where('id', 82)->get()->first();
        $categorie->slug = 'tendeur-chain-distrib';
        $categorie->save();
        $categorie = SousCategorie::where('id', 83)->get()->first();
        $categorie->slug = 'chain-distrib';
        $categorie->save();
        $categorie = SousCategorie::where('id', 84)->get()->first();
        $categorie->slug = 'bougie-allum';
        $categorie->save();
        $categorie = SousCategorie::where('id', 85)->get()->first();
        $categorie->slug = 'bobine-allum';
        $categorie->save();
        $categorie = SousCategorie::where('id', 86)->get()->first();
        $categorie->slug = 'bougie-préchauff';
        $categorie->save();
        $categorie = SousCategorie::where('id', 87)->get()->first();
        $categorie->slug = 'faisc-allum';
        $categorie->save();
        $categorie = SousCategorie::where('id', 88)->get()->first();
        $categorie->slug = 'tête-allum';
        $categorie->save();
        $categorie = SousCategorie::where('id', 89)->get()->first();
        $categorie->slug = 'doigt-allum';
        $categorie->save();
        $categorie = SousCategorie::where('id', 90)->get()->first();
        $categorie->slug = 'temp-préchauff';
        $categorie->save();
        $categorie = SousCategorie::where('id', 91)->get()->first();
        $categorie->slug = 'allumeur';
        $categorie->save();
        $categorie = SousCategorie::where('id', 92)->get()->first();
        $categorie->slug = 'capt-cliqueti';
        $categorie->save();
        $categorie = SousCategorie::where('id', 93)->get()->first();
        $categorie->slug = 'mod-allum';
        $categorie->save();
        $categorie = SousCategorie::where('id', 94)->get()->first();
        $categorie->slug = 'sonde-lambda';
        $categorie->save();
        $categorie = SousCategorie::where('id', 95)->get()->first();
        $categorie->slug = 'silencieux-ar';
        $categorie->save();
        $categorie = SousCategorie::where('id', 96)->get()->first();
        $categorie->slug = 'vanne-egr';
        $categorie->save();
        $categorie = SousCategorie::where('id', 97)->get()->first();
        $categorie->slug = 'joint-échappmnt';
        $categorie->save();
        $categorie = SousCategorie::where('id', 98)->get()->first();
        $categorie->slug = 'fix-potéchappmnt';
        $categorie->save();
        $categorie = SousCategorie::where('id', 99)->get()->first();
        $categorie->slug = 'silencieux-inter';
        $categorie->save();
        $categorie = SousCategorie::where('id', 100)->get()->first();
        $categorie->slug = 'kit-assbl-syséchappmnt';
        $categorie->save();
        $categorie = SousCategorie::where('id', 101)->get()->first();
        $categorie->slug = 'collier-échappmnt';
        $categorie->save();
        $categorie = SousCategorie::where('id', 102)->get()->first();
        $categorie->slug = 'tuyau-échappmnt';
        $categorie->save();
        $categorie = SousCategorie::where('id', 103)->get()->first();
        $categorie->slug = 'tress-échappmnt';
        $categorie->save();
        $categorie = SousCategorie::where('id', 104)->get()->first();
        $categorie->slug = 'turbocompresseur';
        $categorie->save();
        $categorie = SousCategorie::where('id', 105)->get()->first();
        $categorie->slug = 'catalyseur';
        $categorie->save();
        $categorie = SousCategorie::where('id', 106)->get()->first();
        $categorie->slug = 'filtr-particul';
        $categorie->save();
        $categorie = SousCategorie::where('id', 107)->get()->first();
        $categorie->slug = 'silencieux-av';
        $categorie->save();
        $categorie = SousCategorie::where('id', 108)->get()->first();
        $categorie->slug = 'kit-assbl-silenc';
        $categorie->save();
        $categorie = SousCategorie::where('id', 109)->get()->first();
        $categorie->slug = 'kit-assbl-cat';
        $categorie->save();
        $categorie = SousCategorie::where('id', 110)->get()->first();
        $categorie->slug = 'collect-échappmnt';
        $categorie->save();
        $categorie = SousCategorie::where('id', 111)->get()->first();
        $categorie->slug = 'protec-therm-échappmnt';
        $categorie->save();
        $categorie = SousCategorie::where('id', 112)->get()->first();
        $categorie->slug = 'embou-échappmnt';
        $categorie->save();
        $categorie = SousCategorie::where('id', 113)->get()->first();
        $categorie->slug = 'kit-mont-collect-gazéchap';
        $categorie->save();
        $categorie = SousCategorie::where('id', 114)->get()->first();
        $categorie->slug = 'filtr-huil';
        $categorie->save();
        $categorie = SousCategorie::where('id', 115)->get()->first();
        $categorie->slug = 'filtr-air';
        $categorie->save();
        $categorie = SousCategorie::where('id', 116)->get()->first();
        $categorie->slug = 'filtr-habitacl';
        $categorie->save();
        $categorie = SousCategorie::where('id', 117)->get()->first();
        $categorie->slug = 'filtr-carbur';
        $categorie->save();
        $categorie = SousCategorie::where('id', 118)->get()->first();
        $categorie->slug = 'filtr-air-sport';
        $categorie->save();
        $categorie = SousCategorie::where('id', 119)->get()->first();
        $categorie->slug = 'vérin-hayon';
        $categorie->save();
        $categorie = SousCategorie::where('id', 120)->get()->first();
        $categorie->slug = 'rétrovis-ext';
        $categorie->save();
        $categorie = SousCategorie::where('id', 121)->get()->first();
        $categorie->slug = 'feu-ar';
        $categorie->save();
        $categorie = SousCategorie::where('id', 122)->get()->first();
        $categorie->slug = 'glace-rétrovis';
        $categorie->save();
        $categorie = SousCategorie::where('id', 123)->get()->first();
        $categorie->slug = 'phares';
        $categorie->save();
        $categorie = SousCategorie::where('id', 124)->get()->first();
        $categorie->slug = 'feu-clignotant';
        $categorie->save();
        $categorie = SousCategorie::where('id', 125)->get()->first();
        $categorie->slug = 'pare-boue';
        $categorie->save();
        $categorie = SousCategorie::where('id', 126)->get()->first();
        $categorie->slug = 'anti-brouillard';
        $categorie->save();
        $categorie = SousCategorie::where('id', 127)->get()->first();
        $categorie->slug = 'grill-pare-choc';
        $categorie->save();
        $categorie = SousCategorie::where('id', 128)->get()->first();
        $categorie->slug = 'écl-plaqimmatric';
        $categorie->save();
        $categorie = SousCategorie::where('id', 129)->get()->first();
        $categorie->slug = 'poignée-porte';
        $categorie->save();
        $categorie = SousCategorie::where('id', 130)->get()->first();
        $categorie->slug = 'pare-choc';
        $categorie->save();
        $categorie = SousCategorie::where('id', 131)->get()->first();
        $categorie->slug = 'grille-callandre';
        $categorie->save();
        $categorie = SousCategorie::where('id', 132)->get()->first();
        $categorie->slug = 'vérin-capot';
        $categorie->save();
        $categorie = SousCategorie::where('id', 133)->get()->first();
        $categorie->slug = 'aile';
        $categorie->save();
        $categorie = SousCategorie::where('id', 134)->get()->first();
        $categorie->slug = 'coque-rétrovis';
        $categorie->save();
        $categorie = SousCategorie::where('id', 135)->get()->first();
        $categorie->slug = 'supp-pare-choc';
        $categorie->save();
        $categorie = SousCategorie::where('id', 136)->get()->first();
        $categorie->slug = 'portes-comp';
        $categorie->save();
        $categorie = SousCategorie::where('id', 137)->get()->first();
        $categorie->slug = 'capot';
        $categorie->save();
        $categorie = SousCategorie::where('id', 138)->get()->first();
        $categorie->slug = 'feu-stop-add';
        $categorie->save();
        $categorie = SousCategorie::where('id', 139)->get()->first();
        $categorie->slug = 'attellage-remorq';
        $categorie->save();
        $categorie = SousCategorie::where('id', 140)->get()->first();
        $categorie->slug = 'baguette';
        $categorie->save();
        $categorie = SousCategorie::where('id', 141)->get()->first();
        $categorie->slug = 'face-av';
        $categorie->save();
        $categorie = SousCategorie::where('id', 142)->get()->first();
        $categorie->slug = 'renf-pare-choc';
        $categorie->save();
        $categorie = SousCategorie::where('id', 143)->get()->first();
        $categorie->slug = 'bas-caisse';
        $categorie->save();
        $categorie = SousCategorie::where('id', 144)->get()->first();
        $categorie->slug = 'catadioptre-ar';
        $categorie->save();
        $categorie = SousCategorie::where('id', 145)->get()->first();
        $categorie->slug = 'feu-brouill-ar';
        $categorie->save();
        $categorie = SousCategorie::where('id', 146)->get()->first();
        $categorie->slug = 'ferm-centr';
        $categorie->save();
        $categorie = SousCategorie::where('id', 147)->get()->first();
        $categorie->slug = 'serr-hayon';
        $categorie->save();
        $categorie = SousCategorie::where('id', 148)->get()->first();
        $categorie->slug = 'spoiler-pare-choc';
        $categorie->save();
        $categorie = SousCategorie::where('id', 149)->get()->first();
        $categorie->slug = 'cach-moteur';
        $categorie->save();
        $categorie = SousCategorie::where('id', 150)->get()->first();
        $categorie->slug = 'feu-position';
        $categorie->save();
        $categorie = SousCategorie::where('id', 151)->get()->first();
        $categorie->slug = 'élarg-aile';
        $categorie->save();
        $categorie = SousCategorie::where('id', 152)->get()->first();
        $categorie->slug = 'feu-diurne';
        $categorie->save();
        $categorie = SousCategorie::where('id', 153)->get()->first();
        $categorie->slug = 'passage-roue';
        $categorie->save();
        $categorie = SousCategorie::where('id', 154)->get()->first();
        $categorie->slug = 'hayon-coffre';
        $categorie->save();
        $categorie = SousCategorie::where('id', 155)->get()->first();
        $categorie->slug = 'joint-vitre';
        $categorie->save();
        $categorie = SousCategorie::where('id', 156)->get()->first();
        $categorie->slug = 'verre-phare';
        $categorie->save();
        $categorie = SousCategorie::where('id', 157)->get()->first();
        $categorie->slug = 'joint-porte';
        $categorie->save();
        $categorie = SousCategorie::where('id', 158)->get()->first();
        $categorie->slug = 'feu-recul';
        $categorie->save();
        $categorie = SousCategorie::where('id', 159)->get()->first();
        $categorie->slug = 'emblèmes';
        $categorie->save();
        $categorie = SousCategorie::where('id', 160)->get()->first();
        $categorie->slug = 'feu-stop';
        $categorie->save();
        $categorie = SousCategorie::where('id', 161)->get()->first();
        $categorie->slug = 'longeron';
        $categorie->save();
        $categorie = SousCategorie::where('id', 162)->get()->first();
        $categorie->slug = 'amortisseur';
        $categorie->save();
        $categorie = SousCategorie::where('id', 163)->get()->first();
        $categorie->slug = 'coupel-amortis';
        $categorie->save();
        $categorie = SousCategorie::where('id', 164)->get()->first();
        $categorie->slug = 'ressort-susp';
        $categorie->save();
        $categorie = SousCategorie::where('id', 165)->get()->first();
        $categorie->slug = 'souff-amort-butée-elastiq';
        $categorie->save();
        $categorie = SousCategorie::where('id', 166)->get()->first();
        $categorie->slug = 'kit-ressort';
        $categorie->save();
        $categorie = SousCategorie::where('id', 167)->get()->first();
        $categorie->slug = 'patin-ressort';
        $categorie->save();
        $categorie = SousCategorie::where('id', 168)->get()->first();
        $categorie->slug = 'lame-ressort';
        $categorie->save();
        $categorie = SousCategorie::where('id', 169)->get()->first();
        $categorie->slug = 'susp-pneumatiq';
        $categorie->save();
        $categorie = SousCategorie::where('id', 170)->get()->first();
        $categorie->slug = 'susp-ressort-amort';
        $categorie->save();
        $categorie = SousCategorie::where('id', 171)->get()->first();
        $categorie->slug = 'accum-susp';
        $categorie->save();
        $categorie = SousCategorie::where('id', 172)->get()->first();
        $categorie->slug = 'essuie-glace';
        $categorie->save();
        $categorie = SousCategorie::where('id', 173)->get()->first();
        $categorie->slug = 'bras-essuie-glace';
        $categorie->save();
        $categorie = SousCategorie::where('id', 174)->get()->first();
        $categorie->slug = 'pomp-lavglace';
        $categorie->save();
        $categorie = SousCategorie::where('id', 175)->get()->first();
        $categorie->slug = 'moteur-essuie-glace';
        $categorie->save();
        $categorie = SousCategorie::where('id', 176)->get()->first();
        $categorie->slug = 'tringl-essuie';
        $categorie->save();
        $categorie = SousCategorie::where('id', 177)->get()->first();
        $categorie->slug = 'gicl-essuie-glace';
        $categorie->save();
        $categorie = SousCategorie::where('id', 178)->get()->first();
        $categorie->slug = 'bocal-lavglace';
        $categorie->save();
        $categorie = SousCategorie::where('id', 179)->get()->first();
        $categorie->slug = 'caoutch-essuie-glace';
        $categorie->save();
        $categorie = SousCategorie::where('id', 180)->get()->first();
        $categorie->slug = 'calorstat';
        $categorie->save();
        $categorie = SousCategorie::where('id', 181)->get()->first();
        $categorie->slug = 'pomp-eau';
        $categorie->save();
        $categorie = SousCategorie::where('id', 182)->get()->first();
        $categorie->slug = 'rad-refroid-moteur';
        $categorie->save();
        $categorie = SousCategorie::where('id', 183)->get()->first();
        $categorie->slug = 'sonde-temp-liq-refroid';
        $categorie->save();
        $categorie = SousCategorie::where('id', 184)->get()->first();
        $categorie->slug = 'expvase-liq-réfroid';
        $categorie->save();
        $categorie = SousCategorie::where('id', 185)->get()->first();
        $categorie->slug = 'bouchon-liq-réfroid';
        $categorie->save();
        $categorie = SousCategorie::where('id', 186)->get()->first();
        $categorie->slug = 'échangeur-air';
        $categorie->save();
        $categorie = SousCategorie::where('id', 187)->get()->first();
        $categorie->slug = 'ventil-radiat';
        $categorie->save();
        $categorie = SousCategorie::where('id', 188)->get()->first();
        $categorie->slug = 'interrup-temp-ventil';
        $categorie->save();
        $categorie = SousCategorie::where('id', 189)->get()->first();
        $categorie->slug = 'rad-huil';
        $categorie->save();
        $categorie = SousCategorie::where('id', 190)->get()->first();
        $categorie->slug = 'embr-ventil-rad';
        $categorie->save();
        $categorie = SousCategorie::where('id', 191)->get()->first();
        $categorie->slug = 'bouchon-rad';
        $categorie->save();
        $categorie = SousCategorie::where('id', 192)->get()->first();
        $categorie->slug = 'antigel';
        $categorie->save();
        $categorie = SousCategorie::where('id', 193)->get()->first();
        $categorie->slug = 'rotule-direct';
        $categorie->save();
        $categorie = SousCategorie::where('id', 194)->get()->first();
        $categorie->slug = 'rotule-axiale';
        $categorie->save();
        $categorie = SousCategorie::where('id', 195)->get()->first();
        $categorie->slug = 'souff-direct';
        $categorie->save();
        $categorie = SousCategorie::where('id', 196)->get()->first();
        $categorie->slug = 'bielte-direct';
        $categorie->save();
        $categorie = SousCategorie::where('id', 197)->get()->first();
        $categorie->slug = 'pomp-hydr-direct-assist';
        $categorie->save();
        $categorie = SousCategorie::where('id', 198)->get()->first();
        $categorie->slug = 'huil-hydr';
        $categorie->save();
        $categorie = SousCategorie::where('id', 199)->get()->first();
        $categorie->slug = 'crémaill-direct';
        $categorie->save();
        $categorie = SousCategorie::where('id', 200)->get()->first();
        $categorie->slug = 'amort-direct';
        $categorie->save();
        $categorie = SousCategorie::where('id', 201)->get()->first();
        $categorie->slug = 'liq-direct-assist';
        $categorie->save();
        $categorie = SousCategorie::where('id', 202)->get()->first();
        $categorie->slug = 'capt-angl-braq';
        $categorie->save();
        $categorie = SousCategorie::where('id', 203)->get()->first();
        $categorie->slug = 'colonn-direct-assist-direct';
        $categorie->save();
    }
}
